// Sample sites/xmpl-angular/src/app/pages/content/content.component.ts
import { Component, OnDestroy } from '@angular/core';

@Component({
  selector: 'app-content',
  templateUrl: './content.component.html',
  styleUrls: ['./content.component.css']
})
export class ContentComponent implements OnDestroy {
  ngOnDestroy() : void {
    (window as any).xmpProvider.trackEvent.trackingLeave()
  }
}

<div
			class='is-preload'
			xmp-personalized-controller="true"
			xmp-tracking-page-name='Content Page'
		>
			<div id='wrapper'>
				<app-header></app-header>

				<div id='main' class='alt'>
					<section id='one' xmp-class='xmp.r.backgroundColor'>
						<div class='inner'>
							<header class='major'>
								<h1>
									<span xmp-text='xmp.r.preference'></span> holiday destinations
								</h1>
							</header>
							<span class='image main'>
								<img
									alt=''
									xmp-image-asset='xmp.r.photo5'
								/>
							</span>
							<span xmp-text='xmp.r.promoText'></span>
						</div>
					</section>
          <app-contact></app-contact>
          <app-footer></app-footer>
				</div>
			</div>
		</div>

// Sample sites/xmpl-react/src/pages/Content.js
/* eslint-disable react/style-prop-object */
import { useEffect } from 'react'
import { Contact } from '../components/Contact'
import { Footer } from '../components/Footer'
import { Header } from '../components/Header'
import { useXmpl } from '../helpers/utils'

export const Content = () => {
  useXmpl()

  useEffect(() => {
		return () => {
			window.xmpProvider.trackEvent.trackingLeave()
		}
	}, [])

	return (
		<div
			className='is-preload'
			xmp-personalized-controller="true"
			xmp-tracking-page-name='Content Page'
		>
			<div id='wrapper'>
				<Header />

				<div id='main' className='alt'>
					<section id='one' xmp-class='xmp.r.backgroundColor'>
						<div className='inner'>
							<header className='major'>
								<h1 style={{ textTransform: 'capitalize'}}>
									<span xmp-text='xmp.r.preference'></span> holiday destinations
								</h1>
							</header>
							<span className='image main'>
								<img
									alt=''
									xmp-image-asset='xmp.r.photo5'
								/>
							</span>
							<span xmp-text='xmp.r.promoText'></span>
						</div>
					</section>
          <Contact />
          <Footer />
				</div>
			</div>
		</div>
	)
}
