// Sample sites/xmpl-react/src/components/Header.js
import { useState } from "react"
import { Link } from "react-router-dom"
import logoIcon from './../assets/RoundTravel_Logo.png'

/* eslint-disable jsx-a11y/anchor-is-valid */
export const Header = () => {
	const [ isShowMenu, setShowMenu ] = useState(false)
	const showMenu = (e) => {
		e.preventDefault()
		setShowMenu(!isShowMenu)
	}
	return (
		<>
			<header id='header' className='alt'>
				<Link to='/' className='logo'>
					<img src={logoIcon} alt="Round Travel" />
				</Link>
				<nav>
					<a onClick={showMenu}>Menu</a>
				</nav>
			</header>

			<nav className={isShowMenu && 'visible'} id='menu' onClick={showMenu}>
				<ul className='links'>
					<li>
						<Link to='/'>Home Page</Link>
					</li>
					<li>
						<Link to='/content' xmp-tracking-action='Clicked Content'>
							Content Page
						</Link>
					</li>
					<li>
						<a href='https://www.xmpie.com' xmp-tracking-action='Clicked XMPie'>
							XMPie Website
						</a>
					</li>
					<li>
						<a
							href='https://campus.xmpie.com'
							xmp-tracking-action='Clicked Campus'
						>
							XMPie Campus
						</a>
					</li>
				</ul>
				<ul className='actions stacked'>
					<li>
						<Link to='/' className='button primary fit'>
							Get Started
						</Link>
					</li>
				</ul>
			</nav>
		</>
	)
}

// Sample sites/xmpl-angular/src/app/shared/header/header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent {
  logoSrc = 'assets/images/RoundTravel_Logo.png'
  isShowMenu = false

  showMenu($event: any) {
    $event.preventDefault()
    this.isShowMenu = true
  }

  hideMenu() {
    this.isShowMenu = false
  }
}

<header id="header" class="alt">
  <a routerLink="/" class="logo">
    <img [src]="logoSrc" alt="Round Travel" />
  </a>
  <nav>
    <a (click)="showMenu($event)" href="#menu">Menu</a>
  </nav>
</header>

<nav [class.visible]="isShowMenu" id="menu" (click)="hideMenu()">
  <ul class="links">
    <li>
      <a (click)="hideMenu()" routerLink="/">Home Page</a>
    </li>
    <li>
      <a routerLink="/content" xmp-tracking-action="Clicked Content">
        Content Page
      </a>
    </li>
    <li>
      <a href="https://www.xmpie.com" xmp-tracking-action="Clicked XMPie">
        XMPie Website
      </a>
    </li>
    <li>
      <a href="https://campus.xmpie.com" xmp-tracking-action="Clicked Campus">
        XMPie Campus
      </a>
    </li>
  </ul>
  <ul class="actions stacked">
    <li>
      <a routerLink="/" class="button primary fit"> Get Started </a>
    </li>
  </ul>
</nav>
